# dataset
dataset: CCD
tokenize: none
batch_size: 4
use_tokens: False
model: Huggingface
model_id: eirsteir/crs-llama-3-8b-instruct
bf16: True
max_target_length: 512  # TODO: can probably be lower
# Generation parameters
generation_config:
  max_new_tokens: 256  # TODO: can probably be lower
  temperature: 0.0
  top_p: 1.0
  do_sample: False
  top_k: 0
#  max_new_tokens: 512  # TODO: can probably be lower
#  temperature: 0.0
#  top_p: 0.9
#  do_sample: True
  

